#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 30 16:11:47 2018

@author: zeitcai
"""

"""Simple Conference Call Application."""
from flask import Flask, request
from twilio.twiml.voice_response import VoiceResponse, Dial

app = Flask(__name__)

MODERATOR = '+15412578523'


@app.route("/voice", methods=['GET', 'POST'])
def call():
    # Start the TwiML response
    response = VoiceResponse()

    with Dial() as dial:
        # If the caller is our MODERATOR, then start the conference when they
        # join and end the conference when they leave
        if request.values.get('From') == MODERATOR:
            dial.conference(
                'Zeits conference',
                start_conference_on_enter=True,
                end_conference_on_exit=True)
        else:
            # Otherwise have the caller join as a regular participant
            dial.conference('Zeits conference', start_conference_on_enter=False)

    response.append(dial)
    return str(response)

if __name__ == "__main__":
    app.run(debug=True)